version: "3.8"

services:
  split_agpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: split_agpt
    networks:
      - kafka_default


    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - split_to_pop_agpt:/data_split_pop
      - ../../data/AGPT:/input
networks:
  kafka_default:
    external: true

volumes:
  split_to_pop_agpt:
    external: true