version: "3.8"

services:
  populate_ff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: populate_ff
    networks:
      - kafka_default
    depends_on:
      - db_pop_ff
    volumes:
      - split_to_pop_ff:/data_split_pop
      - pop_to_disp_ff:/data_pop_disp

  db_pop_ff:
    container_name: db_pop_ff
    image: mysql:8.0
    networks:
      - kafka_default
    environment:
      - MYSQL_DATABASE=populate_physical_flows
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

networks:
  kafka_default:
    external: true

volumes:
  split_to_pop_ff:
    name: split_to_pop_ff
  pop_to_disp_ff:
    external: true