version: "3.8"

services:
  display_ff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: display_ff
    networks:
      - kafka_default
    ports:
      - 20002:5000
    depends_on:
      - db_disp_ff
    volumes:
      - pop_to_disp_ff:/data_pop_disp

  db_disp_ff:
    container_name: db_disp_ff
    image: mysql:8.0
    networks:
      - kafka_default
    environment:
      - MYSQL_DATABASE=display_ff
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

networks:
  kafka_default:
    external: true

volumes:
  pop_to_disp_ff:
    name: pop_to_disp_ff